[supervisord]
nodaemon=false
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info

[program:prometheus]
command=prometheus
    --config.file=/etc/prometheus/prometheus.yml
    --storage.tsdb.path=/var/lib/prometheus
    --storage.tsdb.retention.time=15d
    --web.listen-address=0.0.0.0:9090
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:grafana]
command=grafana server
    --homepath=/usr/share/grafana
    --config=/etc/grafana/grafana.ini
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
